prompt = """execute `moth show` and if there's a current task, start implementing it.

**ONLY IMPLEMENT THE TASK IN "doing" STATE. NVER CALL `moth done` or move files in the .moth directory** 

** NEVER RUN `git add` or `git commit` **

ask questions as needed. during the session update the existing md under ./moth/doing with information
relevat to feature specification, including decisions taken and rejected. the information in the md should be enough to recreate the feature from the scratch. Under implementation details, don't describe the resulting code changes, only an abstract of how it's done.

use specifications under ./moth/done/ to ensure decision consistency

only expand and correct feature specification, never change it to a different one. e.g. for example if we're implementing addition and there's a request to add logging, the specification should decribe both addition and logging."""
